"""
Driver FSM states for the Rideshare Bot.
Manages driver interaction flow and state transitions.
"""
from telegram.ext import ConversationHandler

# Driver conversation states
DRIVER_REGISTERING_NAME = 1
DRIVER_REGISTERING_PHONE = 2
DRIVER_REGISTERING_VEHICLE = 3
DRIVER_REGISTERING_PLATE = 4
DRIVER_UPLOADING_LICENSE = 5
DRIVER_REGISTERING_LOCATION = 6

DRIVER_IDLE = 10
DRIVER_CONFIRMING_RIDE = 11
DRIVER_ONGOING_RIDE = 12

# State descriptions for debugging
STATE_NAMES = {
    DRIVER_REGISTERING_NAME: "REGISTERING_NAME",
    DRIVER_REGISTERING_PHONE: "REGISTERING_PHONE",
    DRIVER_REGISTERING_VEHICLE: "REGISTERING_VEHICLE",
    DRIVER_REGISTERING_PLATE: "REGISTERING_PLATE",
    DRIVER_UPLOADING_LICENSE: "UPLOADING_LICENSE",
    DRIVER_REGISTERING_LOCATION: "REGISTERING_LOCATION",
    DRIVER_IDLE: "IDLE",
    DRIVER_CONFIRMING_RIDE: "CONFIRMING_RIDE",
    DRIVER_ONGOING_RIDE: "ONGOING_RIDE",
    ConversationHandler.END: "END"
}


def get_state_name(state: int) -> str:
    """Get human-readable state name for logging."""
    return STATE_NAMES.get(state, f"UNKNOWN({state})")
