"""
Rider FSM states for the Rideshare Bot.
Manages rider interaction flow and state transitions.
"""
from telegram.ext import ConversationHandler

# Rider conversation states
RIDER_IDLE = 0
RIDER_REQUESTING_RIDE = 1
RIDER_WAITING_DRIVER = 2
RIDER_RIDE_ASSIGNED = 3
RIDER_ONGOING_RIDE = 4
RIDER_RATING_DRIVER = 5
RIDER_REGISTERING_PHONE = 6
RIDER_MANAGING_FAVORITES = 7
RIDER_SAVING_LOCATION_NAME = 8
RIDER_WAITING_DESTINATION = 9
RIDER_CONFIRMING_ROUTE = 10

# State descriptions for debugging
STATE_NAMES = {
    RIDER_IDLE: "IDLE",
    RIDER_REQUESTING_RIDE: "REQUESTING_RIDE",
    RIDER_WAITING_DRIVER: "WAITING_DRIVER",
    RIDER_RIDE_ASSIGNED: "RIDE_ASSIGNED",
    RIDER_ONGOING_RIDE: "ONGOING_RIDE",
    RIDER_RATING_DRIVER: "RATING_DRIVER",
    RIDER_REGISTERING_PHONE: "REGISTERING_PHONE",
    RIDER_MANAGING_FAVORITES: "MANAGING_FAVORITES",
    RIDER_SAVING_LOCATION_NAME: "SAVING_LOCATION_NAME",
    RIDER_WAITING_DESTINATION: "WAITING_DESTINATION",
    RIDER_CONFIRMING_ROUTE: "CONFIRMING_ROUTE",
    ConversationHandler.END: "END"
}


def get_state_name(state: int) -> str:
    """Get human-readable state name for logging."""
    return STATE_NAMES.get(state, f"UNKNOWN({state})")
